config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import MainView, SearchView

app_name = 'main'

urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
]

users/urls.py
from django.urls import path
from .views import login_view, registration_view, logout_view

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registration_view, name='register'),

]

main/models.py
from django.db import models


class ProductModel(models.Model):
    sku = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    category_productAmount = models.IntegerField(null=True, blank=True)
    discount_price = models.IntegerField(null=True, blank=True)
    full_price = models.IntegerField(null=True, blank=True)
    availability = models.IntegerField(null=True, blank=True)
    orders = models.IntegerField(null=True, blank=True)
    # photos = models.CharField(max_length=1000, null=True, blank=True)

    product_rating = models.FloatField(null=True, blank=True)
    # product_tags = models.CharField(max_length=50, null=True, blank=True)
    seller_id = models.IntegerField(null=True, blank=True)
    seller_title = models.CharField(max_length=70, null=True, blank=True)
    seller_link = models.CharField(max_length=70, null=True, blank=True)
    seller_description = models.TextField(null=True, blank=True)
    seller_registrationDate = models.IntegerField(null=True, blank=True)
    seller_rating = models.FloatField(null=True, blank=True)
    seller_reviews = models.IntegerField(null=True, blank=True)
    seller_orders = models.IntegerField(null=True, blank=True)
    # seller_contacts = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.sku

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ('id',)

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class UserModel(AbstractUser):
    user_image = models.ImageField(upload_to='users/', blank=True, null=True)
    phone_number = models.CharField(max_length=20, default='+998 ')
    following = models.IntegerField(default=0)
    # accept_conditions = models.BooleanField(default=False)

users/forms.py
from django import forms

from .models import UserModel
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'id': "username",
        'class': 'form-control',
        'placeholder': 'username'

    }), label=False)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password'
    }), label=False)


class RegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'id': 'username',
        'type': 'username',
        'name': 'username',
        'class': 'form-control',
        'placeholder': 'username'
    }), label=False)

    email = forms.EmailField(widget=forms.TextInput(attrs={
        'id': "email",
        'type': "email",
        'name': "email",
        'class': 'form-control',
        'placeholder': 'email'
    }), label=False)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password',
        'type': 'password',
        'class': 'form-control pwstrength',
        'data-indicator': 'pwindicator',
        'name': 'password',
        'placeholder': 'password',
    }), label=False)

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password2',
        'type': 'password',
        'name': 'password-confirm',
        'class': 'form-control',
        'placeholder': 'confirm password'
    }), label=False)

    def clean_username(self):
        username = self.cleaned_data['username']
        user = UserModel.objects.get(username=username)
        if user:
            raise ValidationError(f'Ushbu {username} isimli username band')
        return self.cleaned_data['username']

    def clean_confirm_password(self):
        if self.cleaned_data['confirm_password'] != self.cleaned_data['password']:
            raise ValidationError('Parol birhil emas')
        return self.cleaned_data['confirm_password']

main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, View
from .models import ProductModel


class MainView(TemplateView):
    template_name = 'index.html'


class SearchView(ListView):
    template_name = 'index.html'
    model = ProductModel
    # paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = ProductModel.objects.filter(sku__isnull=False)
        return context

    def get_queryset(self):
        qs = ProductModel.objects.filter(sku__isnull=False)
        q = self.request.GET.get('q')
        if q:
            print('123123')
            qs = get_object_or_404(ProductModel, sku=q)

        return qs

users/views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView
from .forms import RegistrationForm, LoginForm
from .models import UserModel
from django.contrib.auth import login, logout, authenticate


def registration_view(request):
    form = RegistrationForm()

    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        print(form)
        if form.is_valid():
            user = UserModel(username=form.cleaned_data['username'])
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('main:home')

    return render(request, 'auth-register.html', context={
        'registration_form': form
    })


def login_view(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if not user is None:
                login(request, user)
                return redirect('main:home')
    return render(request, 'auth-login.html', context={
        'login_form': form
    })


def logout_view(request):
    logout(request)
    return redirect('users:login')

templates/asset/img/unsplash/andre-benz-1214056-unsplash.html
<!DOCTYPE html>
<html>
<head>
<title>File Not Found</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
  background-color: #eee;
}

body, h1, p {
  font-family: "Helvetica Neue", "Segoe UI", Segoe, Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: normal;
  margin: 0;
  padding: 0;
  text-align: center;
}

.container {
  margin-left:  auto;
  margin-right:  auto;
  margin-top: 177px;
  max-width: 1170px;
  padding-right: 15px;
  padding-left: 15px;
}

.row:before, .row:after {
  display: table;
  content: " ";
}

.col-md-6 {
  width: 50%;
}

.col-md-push-3 {
  margin-left: 25%;
}

h1 {
  font-size: 48px;
  font-weight: 300;
  margin: 0 0 20px 0;
}

.lead {
  font-size: 21px;
  font-weight: 200;
  margin-bottom: 20px;
}

p {
  margin: 0 0 10px;
}

a {
  color: #3282e6;
  text-decoration: none;
}
</style>
</head>

<body>
<div class="container text-center" id="error">
  <svg height="100" width="100">
    <polygon points="50,25 17,80 82,80" stroke-linejoin="round" style="fill:none;stroke:#ff8a00;stroke-width:8" />
    <text x="42" y="74" fill="#ff8a00" font-family="sans-serif" font-weight="900" font-size="42px">!</text>
  </svg>
 <div class="row">
    <div class="col-md-12">
      <div class="main-icon text-warning"><span class="uxicon uxicon-alert"></span></div>
        <h1>File not found (404 error)</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <p class="lead">If you think what you're looking for should be here, please contact the site owner.</p>
    </div>
  </div>
</div>

</body>
</html>

templates/asset/img/unsplash/eberhard-grossgasteiger-1207565-unsplash.html
<!DOCTYPE html>
<html>
<head>
<title>File Not Found</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
  background-color: #eee;
}

body, h1, p {
  font-family: "Helvetica Neue", "Segoe UI", Segoe, Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: normal;
  margin: 0;
  padding: 0;
  text-align: center;
}

.container {
  margin-left:  auto;
  margin-right:  auto;
  margin-top: 177px;
  max-width: 1170px;
  padding-right: 15px;
  padding-left: 15px;
}

.row:before, .row:after {
  display: table;
  content: " ";
}

.col-md-6 {
  width: 50%;
}

.col-md-push-3 {
  margin-left: 25%;
}

h1 {
  font-size: 48px;
  font-weight: 300;
  margin: 0 0 20px 0;
}

.lead {
  font-size: 21px;
  font-weight: 200;
  margin-bottom: 20px;
}

p {
  margin: 0 0 10px;
}

a {
  color: #3282e6;
  text-decoration: none;
}
</style>
</head>

<body>
<div class="container text-center" id="error">
  <svg height="100" width="100">
    <polygon points="50,25 17,80 82,80" stroke-linejoin="round" style="fill:none;stroke:#ff8a00;stroke-width:8" />
    <text x="42" y="74" fill="#ff8a00" font-family="sans-serif" font-weight="900" font-size="42px">!</text>
  </svg>
 <div class="row">
    <div class="col-md-12">
      <div class="main-icon text-warning"><span class="uxicon uxicon-alert"></span></div>
        <h1>File not found (404 error)</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <p class="lead">If you think what you're looking for should be here, please contact the site owner.</p>
    </div>
  </div>
</div>

</body>
</html>

templates/assets/js/page/features-setting-detail.html
<!DOCTYPE html>
<html>
<head>
<title>File Not Found</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" >
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style type="text/css">
body {
  background-color: #eee;
}

body, h1, p {
  font-family: "Helvetica Neue", "Segoe UI", Segoe, Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: normal;
  margin: 0;
  padding: 0;
  text-align: center;
}

.container {
  margin-left:  auto;
  margin-right:  auto;
  margin-top: 177px;
  max-width: 1170px;
  padding-right: 15px;
  padding-left: 15px;
}

.row:before, .row:after {
  display: table;
  content: " ";
}

.col-md-6 {
  width: 50%;
}

.col-md-push-3 {
  margin-left: 25%;
}

h1 {
  font-size: 48px;
  font-weight: 300;
  margin: 0 0 20px 0;
}

.lead {
  font-size: 21px;
  font-weight: 200;
  margin-bottom: 20px;
}

p {
  margin: 0 0 10px;
}

a {
  color: #3282e6;
  text-decoration: none;
}
</style>
</head>

<body>
<div class="container text-center" id="error">
  <svg height="100" width="100">
    <polygon points="50,25 17,80 82,80" stroke-linejoin="round" style="fill:none;stroke:#ff8a00;stroke-width:8" />
    <text x="42" y="74" fill="#ff8a00" font-family="sans-serif" font-weight="900" font-size="42px">!</text>
  </svg>
 <div class="row">
    <div class="col-md-12">
      <div class="main-icon text-warning"><span class="uxicon uxicon-alert"></span></div>
        <h1>File not found (404 error)</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <p class="lead">If you think what you're looking for should be here, please contact the site owner.</p>
    </div>
  </div>
</div>

</body>
</html>

templates/auth-forgot-password.html
<!DOCTYPE html>
<html lang="en">

<!-- auth-forgot-password.html  Tue, 07 Jan 2020 03:39:47 GMT -->
<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Forgot Password &mdash; CodiePie</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
</head>

<body class="layout-4">
    
<div id="app">
    <section class="section">
        <div class="container mt-5">
            <div class="row">
                <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                    <div class="login-brand">
                        <img src="http://puffintheme.com/craft/codiepie/dist/assets/img/CodiePie-fill.svg" alt="logo" width="100" class="shadow-light rounded-circle">
                    </div>
                    <div class="card card-primary">
                        <div class="card-header">
                            <h4>Forgot Password</h4>
                        </div>
                        <div class="card-body">
                            <p class="text-muted">We will send a link to reset your password</p>
                            <form method="POST">
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input id="email" type="email" class="form-control" name="email" tabindex="1" required autofocus>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                                    Forgot Password
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="simple-footer">
                        Copyright &copy; CodiePie 2020
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

<!-- auth-forgot-password.html  Tue, 07 Jan 2020 03:39:47 GMT -->
</html>

templates/auth-login.html
{% load static crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<!-- auth-login.html  Tue, 07 Jan 2020 03:39:47 GMT -->
<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>Login &mdash; CodiePie</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="{% static 'assets/modules/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/modules/fontawesome/css/all.min.css' %}">

<!-- CSS Libraries -->
<link rel="stylesheet" href="{% static 'assets/modules/bootstrap-social/bootstrap-social.css' %}">

<!-- Template CSS -->
<link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/components.min.css' %}">
</head>

<body class="layout-4">

<div id="app">
    <section class="section">
        <div class="container mt-5">
            <div class="row">
                <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                    <div class="login-brand">
                        <img src="http://puffintheme.com/craft/codiepie/dist/assets/img/CodiePie-fill.svg" alt="logo" width="100" class="shadow-light rounded-circle">
                    </div>
                    <div class="card card-primary">
                        <div class="card-header">
                            <h4>Login</h4>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'users:login' %}" class="needs-validation" novalidate="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="email">Username</label>
<!--                                    <input id="email" type="email" class="form-control" name="email" tabindex="1" required autofocus>-->
                                        {{ login_form.username|as_crispy_field }}
                                    <div class="invalid-feedback">
                                        Please fill in your username
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="d-block">
                                        <label for="password" class="control-label">Password</label>
                                        <div class="float-right">
                                            <a href="auth-forgot-password.html" class="text-small">
                                            Forgot Password?
                                            </a>
                                        </div>
                                    </div>
<!--                                    <input id="password" type="password" class="form-control" name="password" tabindex="2" required>-->
                                        {{ login_form.password|as_crispy_field }}
                                    <div class="invalid-feedback">
                                        please fill in your password
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me">
                                        <label class="custom-control-label" for="remember-me">Remember Me</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-lg btn-block" value="Log In" tabindex="4">Login</button>
                                </div>
                            </form>
                            <div class="text-center mt-4 mb-3">
                                <div class="text-job text-muted">Login With Social</div>
                            </div>
                            <div class="row sm-gutters">
                                <div class="col-6">
                                    <a class="btn btn-block btn-social btn-facebook"><span class="fab fa-facebook"></span> Facebook</a>
                                </div>
                                <div class="col-6">
                                    <a class="btn btn-block btn-social btn-twitter"><span class="fab fa-twitter"></span> Twitter</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-5 text-muted text-center">
                        Don't have an account? <a href="{% url 'users:register' %}">Create One</a>
                    </div>
                    <div class="simple-footer">
                        Copyright &copy; CodiePie 2020
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- General JS Scripts -->
<script src="{% static 'assets/bundles/lib.vendor.bundle.js' %}"></script>
<script src="{% static 'js/CodiePie.js' %}"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>

<!-- auth-login.html  Tue, 07 Jan 2020 03:39:47 GMT -->
</html>

templates/errors-403.html
<!DOCTYPE html>
<html lang="en">

<!-- errors-403.html  Tue, 07 Jan 2020 03:39:48 GMT -->
<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>403 &mdash; CodiePie</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
</head>

<body class="layout-4">

<div id="app">
    <section class="section">
        <div class="container mt-5">
            <div class="page-error">
                <div class="page-inner">
                    <h1>403</h1>
                    <div class="page-description">You do not have access to this page.</div>
                    <div class="page-search">
                        <form>              	
                            <div class="form-group floating-addon floating-addon-not-append">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-search"></i></div>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary btn-lg">Search</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="mt-3">
                            <a href="index-2.html">Back to Home</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="simple-footer mt-5">Copyright &copy; CodiePie 2020</div>
        </div>
    </section>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

<!-- errors-403.html  Tue, 07 Jan 2020 03:39:48 GMT -->
</html>

templates/errors-404.html
<!DOCTYPE html>
<html lang="en">

<!-- errors-404.html  Tue, 07 Jan 2020 03:39:48 GMT -->
<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>404 &mdash; CodiePie</title>

<!-- General CSS Files -->
<link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="assets/css/style.min.css">
<link rel="stylesheet" href="assets/css/components.min.css">
</head>

<body class="layout-4">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <span class="loader"><span class="loader-inner"></span></span>
</div>

<div id="app">
    <section class="section">
        <div class="container mt-5">
            <div class="page-error">
                <div class="page-inner">
                    <h1>404</h1>
                    <div class="page-description">
                        The page you were looking for could not be found.
                    </div>
                    <div class="page-search">
                        <form>
                            <div class="form-group floating-addon floating-addon-not-append">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fas fa-search"></i></div>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary btn-lg">Search</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="mt-3"><a href="index-2.html">Back to Home</a></div>
                    </div>
                </div>
            </div>
            <div class="simple-footer mt-5">Copyright &copy; CodiePie 2020</div>
        </div>
    </section>
</div>

<!-- General JS Scripts -->
<script src="assets/bundles/lib.vendor.bundle.js"></script>
<script src="js/CodiePie.js"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="js/scripts.js"></script>
<script src="js/custom.js"></script>
</body>

<!-- errors-404.html  Tue, 07 Jan 2020 03:39:48 GMT -->
</html>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--   Tue, 07 Jan 2020 03:33:27 GMT -->
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Ecommerce Dashboard &mdash; CodiePie</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/modules/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/fontawesome/css/all.min.css' %}">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{% static 'assets/modules/jqvmap/dist/jqvmap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/summernote/summernote-bs4.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/owlcarousel2/dist/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/owlcarousel2/dist/assets/owl.theme.default.min.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/components.min.css' %}">

</head>

{% include 'layouts/inc/navbar.html' %}

{% block script %}

<!-- General JS Scripts -->
<script src="{% static 'assets/bundles/lib.vendor.bundle.js' %}"></script>
<script src="{% static 'js/CodiePie.js' %}"></script>

<!-- JS Libraies -->
<script src="{% static 'assets/modules/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'assets/modules/chart.min.js' %}"></script>
<script src="{% static 'assets/modules/owlcarousel2/dist/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/modules/summernote/summernote-bs4.js' %}"></script>
<script src="{% static 'assets/modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

<!-- Page Specific JS File -->
<script src="{% static 'js/page/index.js' %}"></script>

<!-- Template JS File -->
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

{% endblock %}

templates/layouts/inc/footer.html
<!-- Start app Footer part -->
<footer class="main-footer">
    <div class="footer-left">
        <div class="bullet"></div>
        <a href="templateshub.net">Templates Hub</a>
    </div>
    <div class="footer-right">

    </div>
</footer>